### ISSUE TITLE
EnvironmentNameNotFound: Could not find conda environment: ldm

### ISSUE THREAD

**Issue by IIIIIIIllllllllIIIII** [glonlas/Stable-Diffusion-Apple-Silicon-M1-Install#11]
```
Congratulation! Your environment is installed


What do you want to do?
   1) Install Stable Diffusion
   2) Run Stable Diffusion in Browser
   3) Run Stable Diffusion in Terminal
   4) Upscale a picture with Real-ESRGAN upscaler
   5) Uninstall Stable Diffusion
   6) Exit
Select an option [1-6]: 2
Starting Stable Diffusion Web UI

EnvironmentNameNotFound: Could not find conda environment: ldm
You can list all discoverable environments with `conda info --envs`.


Reload your browser page once the command below will be showing 'Started Stable Diffusion dream server!'
Traceback (most recent call last):
  File "/Users/bamboozle/stable-diffusion/InvokeAI/scripts/dream.py", line 5, in <module>
    import invoke
  File "/Users/bamboozle/stable-diffusion/InvokeAI/scripts/invoke.py", line 19, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'
(base) ➜  stable-diffusion 

```

**Comment by IIIIIIIllllllllIIIII** [comment]
seems the environment-mac.yaml is named .yml and thus not found.... lets see if the additional file in the folder fixes the installation process
